import type { PullRequestLabel } from "../domain.js"

const pick = <A>(items: readonly A[], index: number): A => items[((index % items.length) + items.length) % items.length]!

const people = ["mira", "devon", "nina", "oscar", "mina", "buster", "jules", "tess", "rowan", "kai"] as const

const labels: readonly PullRequestLabel[][] = [
	[],
	[{ name: "bug", color: "#d73a4a" }],
	[{ name: "enhancement", color: "#a2eeef" }],
	[{ name: "ui", color: "#c5def5" }],
	[{ name: "performance", color: "#fbca04" }],
	[
		{ name: "tests", color: "#0e8a16" },
		{ name: "refactor", color: "#d4c5f9" },
	],
]

const pullRequestTitles = [
	"fix(provider): align Anthropic Opus 4.5 efforts",
	"fix(provider): constrain OpenAI deep research efforts",
	"fix(i18n): complete Simplified Chinese translations",
	"fix(provider): align GPT-5 reasoning variants",
	"feat(desktop): add export logs archive",
	"fix(cli): forward signals from npm shim",
	"fix(tui): retain cleared prompt drafts",
	"feat(databricks): add Model Serving and AI Gateway provider",
	"chore: update GitHub actions and pin SHAs",
	"feat(desktop): allow silent user-wide install",
	"improve go sub animation performance",
	"add agent browser panel",
	"tui: update plan pay-as-you-go message",
	"use keymap state for layer visibility",
	"feat(opencode): add /menu slash command",
	"fix: force OAuth flow for unauthenticated MCP servers",
	"fix(session): prevent double compaction",
	"feat(tui): add Neovim editor context polling",
	"fix(provider): propagate options.extraBody",
	"docs(ecosystem): add Paseo entry",
	"feat(websearch): add Parallel provider rollout",
	"chore: upgrade SST version",
	"feat(desktop): show working indicator in project sidebar",
	"fix: avoid reasoningEffort for GPT-5.5",
	"fix(tui): defer streaming updates during permission prompts",
	"fix(opencode): plugin auto-update cleanup",
	"feat(core): allow external workspace creation",
	"feat(tui): render clickable links in terminal output",
	"chore(husky): add bun to PATH in pre-push hook",
	"fix(desktop): ensure Electron binary before predev",
	"feat: add server-owned steer queue pending messages",
	"fix(tui): capture Home and End in prompt normal mode",
	"feat(cli): fish and zsh shell completion",
	"fix(session): add fallback retry handling",
	"feat(core): copy file changes when warping",
	"chore: track model variant in honeycomb",
	"fix(session): avoid repeated compaction of retained tail",
	"fix(session): exclude orphaned interrupted tools",
	"fix: clamp reasoning tokens in session usage",
	"fix(tui): restore custom provider in /connect",
	"fix(session): retry empty stream truncations with attempt cap",
	"feat: add image model switch",
	"feat: add progress and cancel notifications",
	"docs: add AgentDrop MCP server example",
	"fix(cli): detect MIME type for --file flag",
	"fix(opencode): handle cancel in upgrade process",
	"refactor(desktop): convert main process to Effect",
	"fix: add child process close fallback on Windows",
	"docs(desktop): update README for Electron",
] as const

const branchTopics = [
	"reasoning-effort-anthropic",
	"reasoning-effort-openai-o-series",
	"fix-zh-i18n-completeness",
	"fix-gpt55-minimal-variant",
	"window-recovery",
	"fix-opencode-shim-signal-forwarding",
	"tui-draft-retention-history",
	"feat-databricks-provider",
	"pin-actions",
	"desktop-user-installer-updates",
	"go-sub-anim-buffered",
	"feature-agent-browser-v1",
	"zen-workspace-msg",
	"use-keymap-state",
	"feat-menu-slash-command",
	"fix-mcp-oauth-false-success",
	"fix-double-compaction",
	"nvim-support",
	"fix-openai-compatible-extra-body",
	"ecosystem-paseo",
	"parallel-web-search",
	"upgrade-sst-version",
	"working-indicator",
	"fix-gpt-5-5-reasoning-effort",
	"fix-tui-permission-stream-crash",
	"fix-plugin-auto-update-and-cleanup",
	"workspace-external",
	"feat-open-url-on-right-click",
	"husky-pre-push-bun-path",
	"desktop-predev-electron-postinstall",
	"prompt-steer-queue-draft",
] as const

const issueTitles = [
	"fix: custom provider dialog does not expose attachment toggle",
	"[FEATURE]: Streaming output renders word-by-word causing distracting reflow",
	"Bug: custom provider models cannot use image attachment",
	"[FEATURE]: Font size adjustment",
	"Does not support non-ASCII paths and filenames",
	"[FEATURE]: Show reasoning variant for subagents in the UI",
	"Bug: 404 Not Found when adding a custom Gemini provider",
	"opencode desktop does not respond with zen model",
	"Extremely slow performance with OpenCode on Ubuntu",
	"Desktop shows modified files as unmodified",
	"MCP failed to get tools from Stitch proxy",
	"An error during launch of opencode beta",
	"Where are normal Windows desktop builds",
	"[FEATURE]: support resolving file tags from external editor output",
	"[FEATURE]: allow compact host-rendered sidebar sections",
	"C# LSP does not load on Razor extensions",
	"Monthly token quota ends too early",
	"Silent completion failure for OpenRouter FOSS models",
	"[FEATURE]: highlight color looks like clickable links",
	"Keybinds using keymap not recognized",
	"[FEATURE]: support manually installed CLI in VS Code extension",
	"Can we add /copy-last for only the last response",
	"[FEATURE]: add /menu slash command alternative to Ctrl+P",
	"MCP toggle not working",
	"[FEATURE]: Neovim editor context support in the TUI",
	"Double compaction for Copilot Opus 4.7",
	"Show subagent output in opencode run",
	"macOS Desktop notifications do not show",
	"Agents get stuck during build commands",
	"Kiro provider crashes with languageModel is not a function",
	"OpenCode enters infinite loop after tool calls complete",
	"GPT-5.5 fails because reasoningEffort is added automatically",
	"TUI blank screen with external plugin on macOS",
	"Antigravity model issues",
	"OpenCode Go API proxy returns cost zero",
	"Windows Desktop cannot use OMO plugin",
	"Desktop sessions missing from Windows sidebar history",
] as const

const pullRequestBodies = [
	"Align Anthropic Opus reasoning variants with provider-supported effort values. Add regression coverage for the Opus mapping.",
	"Document verified OpenAI o-series reasoning effort variants. Constrain deep-research models to their supported medium effort.",
	"Bring the Simplified Chinese locale into parity with the English baseline and fix stale translation keys.",
	"Align GPT-5 reasoning variants across OpenAI, OpenRouter, AI SDK Gateway, and Cloudflare AI Gateway paths.",
	"Add desktop log export archives with scoped renderer, protocol, server, PTY, network, and crash logs.",
	"Forward process signals from the npm shim so Ctrl-C and termination behave like the native binary.",
	"Preserve manually cleared prompt drafts when they contain enough content or prompt parts.",
	"Add Databricks as a custom provider with discovery for Model Serving and AI Gateway surfaces.",
	"Pin GitHub Actions to commit SHAs and update workflow dependencies.",
	"Switch the Windows installer to one-click per-user installs with silent downloaded updates.",
	"Buffer go sub animation state to improve rendering performance in the TUI.",
	"Add an agent-browser backed browser panel with session-scoped tab discovery and takeover controls.",
	"Update the plan pay-as-you-go messaging shown in the workspace flow.",
	"Use keymap state for layer visibility instead of duplicating visibility flags.",
	"Add a built-in /menu slash command that opens the same command menu as Ctrl-P.",
	"Force OAuth when MCP servers accept unauthenticated connections but still require authorization.",
	"Prevent double compaction when a task already has pending compaction state.",
	"Poll Neovim editor context through RPC so the TUI can read the current file and selection.",
	"Propagate options.extraBody for OpenAI-compatible providers without dropping request-specific fields.",
	"Add Paseo to the ecosystem documentation with a one-line markdown table entry.",
	"Add Parallel as a session-stable websearch provider alongside Exa and update provider-specific labels.",
	"Upgrade SST and adjust dependent build configuration.",
	"Show working indicators on the desktop project sidebar while sessions are active.",
	"Avoid sending reasoningEffort for GPT-5.5 where the target endpoint rejects it.",
	"Defer per-session streaming updates while permission prompts are pending, then flush them in order.",
	"Clean up temporary npm residue after plugin auto-update installs and fix stalled updates.",
	"Allow external workspace creation through the core workspace API.",
	"Render clickable URLs in terminal text output and support opening them from the TUI.",
	"Ensure Husky pre-push hooks can find Bun in typical local installations.",
	"Ensure Electron binaries are installed before desktop predev tasks run.",
	"Draft server-owned Steer and Queue pending follow-up messages for review.",
	"Always capture Home and End in prompt normal mode so cursor movement does not scroll the transcript.",
] as const

const issueBodies = [
	"When adding a custom provider through the dialog, image paste fails because the model row never exposes the attachment capability toggle.",
	"Streaming responses render word by word, causing the last line to constantly reflow. Larger buffered chunks would be easier on the eyes.",
	"Custom OpenAI-compatible providers default every model to attachment false, so multimodal models cannot accept images from the prompt input.",
	"Users want Ctrl+mousewheel and keyboard shortcuts for adjusting desktop font size without editing configuration files.",
	"Reading files fails for Japanese and Chinese paths. The CLI should support non-ASCII filenames and paths everywhere it accepts file input.",
	"Subagents show the model name but not the selected reasoning variant, which makes it hard to understand what setting is running.",
	"A company-proxied Gemini custom provider is routed to /chat/completions and returns 404 instead of using the expected endpoint.",
	"The desktop app with a zen model loads the same config as the TUI but does not respond to prompts on Windows.",
	"A comparable workflow takes much longer in OpenCode than Claude Code on the same Ubuntu machine and environment.",
	"The desktop editor view shows files as unmodified even after the underlying files have changed on disk.",
	"The Stitch MCP proxy connects and discovers tools, but OpenCode fails to resolve a schema reference when loading them.",
	"The beta Electron app can fail during launch with a generic application loading error and no clear recovery path.",
	"Users depending on older Windows desktop builds report plugin breakage after the switch to Electron artifacts.",
	"Prompt text written from an external editor does not resolve @filename tags when returning to the TUI.",
	"Host-rendered sidebar sections need an option for compact spacing so dense integrations can fit more useful information.",
	"The C# language server only loads for .cs files even though common .NET extensions include .razor and .cshtml.",
	"A subscription shows fewer usable days than expected, raising questions about token quota accounting.",
	"Several non-default OpenRouter models return no visible completion through OpenCode while direct HTTP requests work.",
	"The current highlight color reads as a link color, which is confusing when the highlighted text is not clickable.",
	"Keybinds configured with keymap are not recognized from tui.json, leaving users unable to override shortcuts.",
	"The VS Code extension cannot find a manually installed opencode binary that is available on PATH.",
	"Users want a /copy-last command to copy only the most recent assistant response instead of the full session transcript.",
	"A slash-command alternative to Ctrl-P would help in IDE terminals where the shortcut conflicts with editor commands.",
	"The MCP toggle appears even after uninstalling related plugins and does nothing when activated.",
	"Neovim users want editor context support through RPC, matching the existing Claude Code IDE and Zed integrations.",
	"Copilot Opus sessions can trigger double compaction and rapidly inflate token usage after model switches.",
	"When opencode run delegates to subagents, users need a way to see subagent output in the console.",
	"Desktop notifications on macOS can silently fail when renderer Notification permission is denied, even though main-process IPC works.",
	"Agents often get stuck during build commands and require manual interruption before the session can continue.",
	"The native Kiro provider fails every request with a languageModel function error.",
] as const

export const mockAuthor = (index: number) => pick(people, index)

export const mockLabels = (index: number): readonly PullRequestLabel[] => pick(labels, index)

export const mockPullRequestTitle = (index: number) => pick(pullRequestTitles, index)

export const mockPullRequestBranch = (index: number) => `${pick(["fix", "feat", "chore", "perf", "ui"], index)}/${pick(branchTopics, index)}-${1000 + index}`

export const mockIssueTitle = (index: number) => pick(issueTitles, index)

export const mockBody = (kind: "issue" | "pull-request", index: number) => {
	if (kind === "pull-request") return pick(pullRequestBodies, index)
	return pick(issueBodies, index)
}
